// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("lightstepreceiver")
	ScopeName = "github.com/zalando/otelcol-lightstep-receiver"
)

const (
	TracesStability = component.StabilityLevelStable
)
